### ISSUE TITLE
Cannot exit the program with y1 empty

### ISSUE THREAD

**Issue by Nate-V** [nathanfarlow/PineappleCAS#11]
When I enter the program with the y1 variable empty, there's no way to exit the program with the calculator, I tried 2nd+quit, on, and y=. The only way to exit is to refresh the program using TI Connect. Can you add a quit button at the bottom? That would be awesome, thanks!

**Comment by nathanfarlow** [comment]
You can exit the program by pressing the clear button. I'll add that to the readme!
