### ISSUE TITLE
PCAS unable to start because of memory issue

### ISSUE THREAD

**Issue by hokuco** [nathanfarlow/PineappleCAS#13]
I see that another user had this same issue, but clearing my ram hasn't helped me like it helped them. Here is the order in which I installed pcas:
1.)downloaded pcas and clibs
2.)uploaded pcas to calculator
3.)uploaded clibs to calculator
4.)archived pcas and reset after getting memory error
5.)still get memory error
What do I do? I have a TI-84 plus CE and am connecting to it over usb with ticonnect for windows.
I use OS version 5.4.0.34 and have 114kb ram available after installing PCAS.

**Comment by adriweb** [comment]
Since you have a recent OS, you can archive basically the programs you're not going to edit, too.
Make sure to also archive all the clibs (should be the default in TI-Connect CE's transfer dialog though)

**Comment by j-tai** [comment]
Archiving prgmPCAS before running it fixes the error for me.

**Comment by hokuco** [comment]
I have no other programs though. Oh wait I'm dumb you actually have to keep pcas in the archive. Oops. Thanks anyways!
