### ISSUE TITLE
Insufficient memory when calling on PCAS in TI-Basic

### ISSUE THREAD

**Issue by Reeperto** [nathanfarlow/PineappleCAS#14]
![Capture 1](https://user-images.githubusercontent.com/19378069/72658929-ffdec300-3974-11ea-91a2-3110c30c71e6.png)

![Capture3-1579323466426](https://user-images.githubusercontent.com/19378069/72658876-657e7f80-3974-11ea-89aa-d27eb7e32fb6.png)
![Capture5-1579323468610](https://user-images.githubusercontent.com/19378069/72658878-67484300-3974-11ea-9683-3fcc726f6581.png)
![Capture4-1579323471698](https://user-images.githubusercontent.com/19378069/72658879-68797000-3974-11ea-8e7d-9f2bc3f31313.png)

Recreate by copying the example derivative program from the readme, unarchive PCAS and run the program.

I also tried to reset the calculator from the memory menu and the reset button on the back. I also archived PCAS and tried to run the program but it comes up with:
![Capture6-1579323546824](https://user-images.githubusercontent.com/19378069/72658891-965eb480-3974-11ea-9472-c617633391b7.png)

**Comment by adriweb** [comment]
You have an extremely outdated OS (5.0.1). Update your OS to the latest one from TI's website. Make sure you have an updated TI Connect CE in order to be able to transfer the OS+Apps bundle file.

**Comment by nathanfarlow** [comment]
In addition to what Adriweb said, check out these other issues to see if they can help:
https://github.com/nathanfarlow/PineappleCAS/issues/13
https://github.com/nathanfarlow/PineappleCAS/issues/8

**Comment by Reeperto** [comment]
Alright that fixed it. Thanks!
