### ISSUE TITLE
Bad Token Error

### ISSUE THREAD

**Issue by whackamadoodle3000** [nathanfarlow/PineappleCAS#16]
How do I get this program onto my calculator? I have a TI-84 Plus CE (OS 5.2.2). When I try to open the 8xp file in TI connect CE it gives this error:
![image](https://user-images.githubusercontent.com/20081655/89703896-0b3f0f00-d904-11ea-90f4-58573ef1c129.png)

Is there another way to put it onto the calculator?

Thanks!

**Comment by nathanfarlow** [comment]
You're on the right track. You're not dragging the file to the right location in TI Connect CE. Take a look at [this youtube tutorial](https://www.youtube.com/watch?v=Ox7v5pNR-dY) on loading games on the calculator. The procedure is the same, but instead of the games, use PCAS.8xp.

**Comment by whackamadoodle3000** [comment]
Thank you! After updating the OS and dragging the PCAS.8xp file to the right place it installed correctly.
