### ISSUE TITLE
On run of PCAS - Error: Invalid

### ISSUE THREAD

**Issue by BinaryShminary** [nathanfarlow/PineappleCAS#18]
Error Message: "Attempted to use a variable or function where it is not valid"

Proceeded as README specified.

About:
TI-84 Plus CE (5.6.0.0020)
PCAS (1.1)
CE C Standard Libraries (8.8)

**Comment by adriweb** [comment]
TI removed the ability to run ASM programs in the latest updates (5.5/5.6). You'll need a jailbreak to continue using that: https://yvantt.github.io/arTIfiCE/
