### ISSUE TITLE
Memory is insufficient to perform the calculation

### ISSUE THREAD

**Issue by adlkas** [nathanfarlow/PineappleCAS#20]
I downloaded Clibs and PCAS and transferred to my Ti 84 Plus CE (OS 5.4) into archive. When I started PCAS, it shows this: Memory is insufficient to perform the calculation. This happens even when this is the only program on my calculator. What should I do to have "enough memory"?

**Comment by nathanfarlow** [comment]
Please take a look at the many closed issues regarding this problem and see if any of their solutions work for you.
