### ISSUE TITLE
Failed.EmptyInput

### ISSUE THREAD

**Issue by BenjaminBruton** [nathanfarlow/PineappleCAS#23]
I have a TI-84 CE with the latest update (5.6) so in addition to Pineapple, I jailbroke with Artifice through CabriJR.

I get to artifice fine and open to the Pineapple menu, but when I attempt to use any of the features, after compiling, they say Failed.EmptyInput.

**Comment by adriweb** [comment]
Try installing (launching once) AsmHook from arTIfiCE, which will allow you to run asm programs from the homescreen like in previous OS versions. PineappleCAS should work better then I suppose.
