### ISSUE TITLE
Error: Memory

### ISSUE THREAD

**Issue by Gopro336** [nathanfarlow/PineappleCAS#25]
I have cleared most everything from my calculator except this program and I get this error when opening. I have calculator version 5.2 so I am running via asm while pcas is in unarchived. I have the c library installed. I have tried multiple inputs in the y1 spot but that doesn't change anything

**Comment by nathanfarlow** [comment]
Can you attach an image of the error?

**Comment by Gopro336** [comment]
![error](https://user-images.githubusercontent.com/63124240/115127928-4ec83d80-9fa8-11eb-8a95-1bc0f31fb6fd.png)

**Comment by Gopro336** [comment]
reset my calc ard reinstalled multiple times same error

**Comment by Gopro336** [comment]
I see in the instructions it says to keep it in the archive to prevent this error, but as I am on 5.2.2 I cannot run it like that.

**Comment by Gopro336** [comment]
and Im not sure if updating to 5.3 is the best idea

**Comment by Gopro336** [comment]
I am able to run it through cesium

**Comment by adriweb** [comment]
You're absolutely fine with 5.3, even with 5.4.0.
Anyway, did you really reset the ram? Depending on your hardware, you may need to hold the reset button for like 2s
