### ISSUE TITLE
Great effort , if you plz we need indifinite integration in new version

### ISSUE THREAD

**Issue by ahmedallahsalem** [nathanfarlow/PineappleCAS#26]
Great effort , if you plz ,we need indifinite integration to be included in new version of the program.

**Comment by adriweb** [comment]
That's extremely, extremely, hard to do :)

**Comment by ahmedallahsalem** [comment]
It may be hard task but still possible , I invite you to think about it ,
there is no app do it except Zoommath which cost a very high price ...
By this application done you turn ti83 to a very powerful calculator .

Regard

Ahmed

**Comment by nathanfarlow** [comment]
As @adriweb said, this is very difficult, and I do not plan to support that in this program.

**Comment by ahmedallahsalem** [comment]
Ok 👍

**Comment by alecautry** [comment]
What about a CAS that can solve indefinite integrals knowing there is a solution? Maybe it can solve using integration by parts or some other similar method? Not perfect but decent.
