### ISSUE TITLE
Bad Token

### ISSUE THREAD

**Issue by trippcgg** [nathanfarlow/PineappleCAS#27]
When I try to put this into the TI Connect CE software, it gives me a bad token error.
![image](https://user-images.githubusercontent.com/87923878/126888764-6bcd6b58-cbe1-43cf-9c92-f214bd7bb47f.png)

**Comment by adriweb** [comment]
in TI Connect CE, you need to transfer it to the calculator (drag n drop it on the calc name), not open it for edition.
