### ISSUE TITLE
Issue with Error: Memory

### ISSUE THREAD

**Issue by Doominator712** [nathanfarlow/PineappleCAS#28]
I have made sure to put it on the system's archive memory and have also downloaded the latest clibs. How much memory does it require to have available to use at all? I am using asmhook and artifice so those might be taking up too much space. Please help.

**Comment by adriweb** [comment]
How much free ram do you have? That's basically the most important point here.

**Comment by Doominator712** [comment]
Alright, I will try that. Thanks!

**Comment by HappyZombieSlayer** [comment]
If that doesn't work, I ended up having to update to OS version 5.6.1 and had to use the jailbreak before I could get the prgmPCAS running. It was all fine after that.

**Comment by Doominator712** [comment]
I got it working! I just had to stop using ASMHook. I did find a different error, maybe. I was doing the equation: (3x^2+3x−6)/(3x+6) in a fraction form. It should simplify to x-1, but instead, it simplified to (in fraction form):
(x^2/(x+2)) + (x/(x+2)) - (2/(x+2)). I don't know if this is something that needs to be fixed or is an error with the syntax. Side note, I put in the (x^2/(x+2)) + (x/(x+2)) - (2/(x+2)) to see if it just needed to simplify it again, but all it did was repeat the answer.

**Comment by adriweb** [comment]
pinging @jacobly0 regarding ASMHook, it's odd that it caused this issue.

**Comment by Doominator712** [comment]
Idk, when I removed it I stopped getting the memory errors  
But do you know what's going on with the above problem?

**Comment by adriweb** [comment]
No idea, that's something specific to this program here, so maybe @nathanfarlow knows

**Comment by Doominator712** [comment]
Update: I fixed the issue. I simply had to upload asmhook to the archive rather than the ram after I implemented PCAS

**Comment by Doominator712** [comment]
Not with the equation though
