### ISSUE TITLE
Bad Token!

### ISSUE THREAD

**Issue by HappyZombieSlayer** [nathanfarlow/PineappleCAS#29]
When opening the file on the Ti Connect app, it responds with a "Bad Token" error. I use a TI-84 Plus CE calculator. What am I doing wrong?

**Comment by adriweb** [comment]
That's normal/expected - you are not supposed to open an assembly program, just transfer it. To do so, drag'n'drop the (8xp) file on the calculator name that appears in the "sidebar" in one of the two first left tabs. Then make sure Archive is selected for the destination (not RAM)

**Comment by HappyZombieSlayer** [comment]
I fixed that, but now when I run the program I get the "ERROR: MEMORY" when running "Asm(prgmPCAS" on my calculator. I'm running version 5.2.2.

**Comment by adriweb** [comment]
Try updating to OS 5.4.0 and archive every program you have. This OS is able to launch archived asm programs directly.

**Comment by HappyZombieSlayer** [comment]
> Try updating to OS 5.4.0 and archive every program you have. This OS is able to launch archived asm programs directly.

When I run prgmPCAS or Asm(prgmPCAS on the calculator I still get "ERROR: MEMORY." The program is archived, along with the rest of my other programs. I have the latest graphics and stuff. I don't understand.
When I ran it as prgmPCAS before having the latest graphics, it popped up a message saying it was missing the file GRAPHX or LibLoad, which means it was doing something right. So what is going wrong?

**Comment by HappyZombieSlayer** [comment]
I'm trying to find some application which allows me to view the .8xp file so I can at least get a sense of what's going on, but it always has the Bad Token error.

**Comment by HappyZombieSlayer** [comment]
Now that I've been thinking for a bit, I think that the issue is the available memory to run the program. The PCAS file is 37kb, but it can only use 32kb of RAM at a time, might this be the issue?

**Comment by adriweb** [comment]
Well it needs "lots" of memory yeah and you should have around 150KB free, pretty much at all times, regardless, as per the memory menu (2nd Plus).
Which is why I said to update to 5.4.0 so that you can archive all your stuff (will not take up ram space anymore).

**Comment by HappyZombieSlayer** [comment]
> Well it needs "lots" of memory yeah and you should have around 150KB free, pretty much at all times, regardless, as per the memory menu (2nd Plus). Which is why I said to update to 5.4.0 so that you can archive all your stuff (will not take up ram space anymore).

Yeah, then I have no idea what is going wrong. I have all of my programs archived, the OS is 5.4.0, and programs other than prgmPCAS are able to run just fine. The only issue is when I do prgmPCAS, because I continuously get the "ERROR: MEMORY".

Maybe this program just isn't compatible for me for whatever reason?

**Comment by HappyZombieSlayer** [comment]
I just updated the OS to 5.6.1 and now when I run prgmPCAS, I get an invalid error:
"ERROR: INVALID
 Attempted to use a variable or function where it is not valid"
This stuff is beyond me, man. Any and all help is appreciated.

**Comment by HappyZombieSlayer** [comment]
I just got it all figured out. It works using the jailbreak tool. Finally! Way too many steps, wish it would have worked on 5.4.0, because life would have been simpler, but I am happy now. Thanks for all the help.

**Comment by adriweb** [comment]
Well I specifically said 5.4.0 not the latest :p
Anyway all good now.
