### ISSUE TITLE
Simplification

### ISSUE THREAD

**Issue by nathanfarlow** [nathanfarlow/PineappleCAS#3]
Simplification of like terms in division, as well as simplification of multi-variable expressions need to be fixed/implemented.

**Comment by nathanfarlow** [comment]
As brought up by @Decimation, multi-variable simplification doesn't work when adding numerical (or maybe other variable?) coefficients:

An example of simplification working:
![multivar1](https://user-images.githubusercontent.com/22306467/41123344-f447ef30-6a63-11e8-8675-ec58f3cabb5f.png)
(Note that the unconventional way that the answer is displayed is a result of exporting the equation)

An example of simplification not working:
![multivar2](https://user-images.githubusercontent.com/22306467/41123350-fbad0670-6a63-11e8-964d-6f6c020edea4.png)

**Comment by Decimation** [comment]
If you can make documentation for your CAS I can try to help.

**Comment by nathanfarlow** [comment]
It only took a year!

![bug1](https://user-images.githubusercontent.com/22306467/59971955-599c1d80-954b-11e9-8a56-a957515d4044.png)
![scr1](https://user-images.githubusercontent.com/22306467/59971956-5b65e100-954b-11e9-9a5e-9b67047caade.png)
