### ISSUE TITLE
"Solver by Nathan Farlow, Calculating... Done."

### ISSUE THREAD

**Issue by Manny9mew** [nathanfarlow/PineappleCAS#37]
Apologies if this is a foolish question, but when I run the program through Artifice, the only thing that appears on my screen is:
"Solver by Nathan Farlow
Calculating...
done."
Is there possibly a download something that I'm missing? 
Thank you.

**Comment by nathanfarlow** [comment]
Seems like  you downloaded the old project before PineappleCAS, [SymbolicDerivative](https://github.com/nathanfarlow/SymbolicDerivative). You should download the latest version of PineappleCAS [here instead](https://github.com/nathanfarlow/PineappleCAS/releases). The program will have the name "PCAS" on your calculator.

**Comment by Manny9mew** [comment]
That was it! Thank you very much, and for the quick reply.
