### ISSUE TITLE
Project Development Canceled?

### ISSUE THREAD

**Issue by LAX18** [nathanfarlow/PineappleCAS#4]
What has come of this project?

**Comment by nathanfarlow** [comment]
I wish I could say it wasn't; there is a great base for a cas here, and only the algorithms need to be implemented. Realistically, development won't resume from me until second semester of school.

**Comment by LAX18** [comment]
I understand. Take your time. I am looking forward to the release!

**Comment by nathanfarlow** [comment]
I appreciate the support!
