### ISSUE TITLE
Failed. Empty Input.

### ISSUE THREAD

**Issue by oklamama** [nathanfarlow/PineappleCAS#40]
Installed PineappleCAS. Tried to run Simplify and get the following...
Parsing input...
Failed. Empty input.
OS Version: 5.3.1.58

**Comment by nathanfarlow** [comment]
You need to type the expression which you want to simplify into Y1. Do that, then launch PineappleCAS and simplify. The output by default will be in Y2.

**Comment by oklamama** [comment]
Thank you! That worked! One more question... i see how the simplify function works. What about evaluate for what x is in an equation? There's no equal sign to input into y1TiffanyOn Aug 15, 2023, at 9:19 PM, Nathan Farlow ***@***.***> wrote:﻿
You need to type the expression which you want to simplify into Y1. Do that, then launch PineappleCAS and simplify. The output by default will be in Y2.

**Comment by nathanfarlow** [comment]
This program can't solve for X in an equality, unfortunately. Your only bet is to use the numerical solver built into the calculator.

**Comment by CoreCount1** [comment]
Hi, I'm on a TI84 plus CE with the firmware that requires artifice. Is there a faster way of simplifying/evaluating/etc than entering equation in y=, pressing apps, selecting CabriJr, scrolling to open, opening artifice, selecting PCAS, selecting eval/simp/etc and then going back to y=? Not exactly a fast process, but I'm not sure if it can be any faster.

> You need to type the expression which you want to simplify into Y1. Do that, then launch PineappleCAS and simplify. The output by default will be in Y2.

**Comment by adriweb** [comment]
For your information, you shouldn't be using artifice manually every time you want to launch an ASM program, that is indeed way too long. The fastest way would be to launch the program "normally" (like older versions) from the program menu, simply, which is made possible by [AsmHook](https://github.com/jacobly0/asmhook) (you can install it by launching it once from artifice). Another way would be to use the [Cesium](https://github.com/mateoconlechuga/cesium) shell which can be opened quickly by [on]+[prgm]. 

if you're looking for something else entirely, check out https://github.com/Hamza-STI/CASYMBA which is another CAS engine program that reads input directly from the Home Screen
