### ISSUE TITLE
Error: Memory with new GUI

### ISSUE THREAD

**Issue by nathanfarlow** [nathanfarlow/PineappleCAS#8]
It seems that we might be pushing the size limits of the binary with the addition of the gui code. When running the program, the calculator displays the Error: Memory screen. The compressed size is 34609 bytes and the decompressed size is 106498 bytes. I'm hoping we can find a way around this by using clever tricks with app vars or updating the toolchain compression or something because otherwise we will need to trim back code and might not have enough room for the TI-BASIC interface.

@adriweb is also kindly looking into the problem so I created the issue to discuss here.

**Comment by adriweb** [comment]
> @adriweb is also kindly looking into the problem.

Yep, although right now I'm about to make a big PR with bug fixes and warning fixes :)

**Comment by nathanfarlow** [comment]
Music to my ears!

**Comment by nathanfarlow** [comment]
Well the problem goes away *for now* if the program is ran when archived. This is what it should be anyway to prevent PCAS from deleting itself with a ram clear. If the calculator's version is the latest this is for the better. I guess we will reopen this issue if the problem comes back.

**Comment by nathanfarlow** [comment]
Quick update: I couldn't replicate the program on an actual calculator: the program runs just fine in RAM and archive. Seems like it might be a CEmu issue
